name: .NET Core Desktop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOTNET_VERSION: "5.0.X"
  BUILD_CONFIG: Release
  BUILD_PLATFORM: X64

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Build solution
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: dotnet publish -c ${{env.BUILD_CONFIG}} /p:Platform=${{env.BUILD_PLATFORM}} -r win-x64 --no-self-contained
        
      - name: SmokeyVersionSwitcher
        uses: actions/upload-artifact@v2
        with:
          name: SmokeyVersionSwitcher
          path: SmokeyVersionSwitcher\bin\x64\Release\net5.0-windows\win-x64\publish
